name: resto
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  flutter_native_splash: ^1.2.1
  flutter_rating_bar: ^4.0.0
  flutter_spinkit: ^5.0.0
  google_fonts: ^2.1.0
  http: ^0.13.3
  lottie: ^1.1.0
  provider: ^5.0.0
  readmore: ^2.1.0
  shimmer: ^2.0.0
  transparent_image: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_native_splash:
  color: "#ffa000"
  image: assets/logo.png
  android: true
  ios: true

flutter:
  uses-material-design: true

  assets:
    - assets/
